### ISSUE TITLE
ckan link no esta bien!

### ISSUE THREAD

**Issue by hmarrao** [ekergy/priceprofor#14]
https://data.lab.fiware.org/dataset/daily-market-hourly-results

**Comment by djuan26** [comment]
He modificado el codigo en el siguiente html, asi que el enlace a fiware en github ahora es el correcto

https://github.com/ekergy/priceprofor/blob/master/wsgi/priceprofor/static/omieinfosysSPA/DataFileGenerator.html

**Comment by hmarrao** [comment]
ya esta arreglado el enlace
