### ISSUE TITLE
[enhancement] La única energía a tener en cuenta es la de bombeo

### ISSUE THREAD

**Issue by cperales** [ekergy/priceprofor#22]
Se me ha ocurrido que, quizás, sea mejor solo tener en cuenta la producción (o consumo) de energía hidráulico de bombeo a la hora de calcular el precio. O, por lo menos, ponderarla más con respecto a las otras.

![instantanea1](https://cloud.githubusercontent.com/assets/17336458/13176960/53ec5f9a-d716-11e5-9c47-3dd84a090423.png)

**Comment by hmarrao** [comment]
Visualmente desde luego, y sin duda que es un indicador de precios altos. En las tablas abajo se puede observar que es la tecnología con mayor precio medio (42€/MWh contra los 32.43€/MWh).
Por ejemplo lo mismo se puede observar para el carbón de importación. 
![instantanea1](https://cloud.githubusercontent.com/assets/1582863/13212869/057869f4-d945-11e5-8b40-7d9211627c57.png)

y se observamos las dos tecnologías juntas ... mejor todavía!

Este tipo de tecnologías son tecnologías con pocas restricciones para disminuir o aumentar la potencia de su generación. O sea son más bien oportunistas o marcadoras de precios altos. esto se espera que sea así la verdad. En esta [página](http://www.energiaysociedad.es/ficha/6-1-formacion-de-precios-en-el-mercado-mayorista-diario-de-electricidad) puedes encontrar algo más de detalle de la formación de precios.

**Comment by hmarrao** [comment]
De todas las formas te animo a construir un modelo de predicción del precio solamente teniendo en cuenta la energia de bombeo. Lo quieres hacer¿?
